### ISSUE TITLE
DeprecationWarning in littleutils

### ISSUE THREAD

**Issue by eirikur-grid** [arni-inaba/log-enricher#12]
The sorcery package has a dependency on a package named littleutils which is causing the following deprecation warnings to appear when I run tests:

```
.../python3.7/site-packages/littleutils/__init__.py:23: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Sized, defaultdict, Mapping, Sequence, MutableMapping
```

There is a newer version of the package available which should fix this. Alternatively, it might be possible to use the `executing` package (https://github.com/alexmojaki/executing) instead of `sorcery` to reduce the dependency footprint.

**Comment by arni-inaba** [comment]
Fixed by removing magic in https://github.com/arni-inaba/log-enricher/commit/9846d6b3b35edab609eedad59a06b2da6ebc122f
